// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("uptime")
	ScopeName = "github.com/yaunj/uptimereceiver/uptimereceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
